language: c
env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.1
before_install:
  # Obtain and install opam locally.
  - mkdir -p ${HOME}/bin
  - wget -O ${HOME}/bin/opam https://github.com/ocaml/opam/releases/download/2.0.0-beta6/opam-2.0.0-beta6-x86_64-linux
  - chmod +x ${HOME}/bin/opam
  - export PATH=$PATH:${HOME}/bin
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  # Initialize the switch.
  - opam init --compiler=${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlbuild ocamlfind bindlib.4.0.5 earley earley-ocaml
  - make
install:
  - make install
script:
  - make tests
os:
  - linux
notifications:
  email:
    - christophe@raffalli.eu
    - rodolphe.lepigre@inria.fr
